version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: 5050
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles   # Volume for collected static files
      - media_volume:/app/media          # Volume for user-uploaded media files
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: "True"
      DATABASE_URL: "postgres://new_user:5050@db:5432/socialmedia"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
    env_file:
      - .env
    working_dir: /app

  nginx:
    image: nginx:latest
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles  # Share static files with NGINX
      - media_volume:/app/media         # Share media files with NGINX
      - ./certs:/etc/ssl/certs          # SSL certificates
    ports:
      - "80:80"
      - "443:443"   # Enable HTTPS
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
